name: Build Torrentinim Docker image
on:
  workflow_dispatch:
  push:
    paths:
      - 'torrentinim-version.txt'
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Read latest release tag
        id: read-tag
        run: |
          echo ::set-output name=tag::$(curl -sL https://raw.githubusercontent.com/arsfeld/torrentinim-build/main/torrentinim-version.txt)
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          repository: 'sergiotapia/torrentinim'
          ref: ${{ steps.read-tag.outputs.tag }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Login to registry
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - 
        name: Push to Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/torrentinim:latest
            ${{ secrets.DOCKER_USERNAME }}/torrentinim:${{ steps.read-tag.outputs.tag }}
